services:
  database:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5431:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file:
      - .env

  backend:
    build: .
    container_name: backend
    command: >
      bash -c "while ! nc -z database 5432; do sleep 1; done &&
        python manage.py collectstatic --noinput &&
        python manage.py migrate --noinput &&
        gunicorn --bind 0.0.0.0:8000 project.wsgi:application"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - database
      
volumes:
  db-data: