# postgres-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: postgres # This name will be used as the HOST in Django settings
  labels:
    app: postgres
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP # Internal service, accessible only within the cluster
    